### ISSUE TITLE
Markdown to Org and/or Markdown to HTML

### ISSUE THREAD

**Issue by Marin-Kitagawa** [smalldev-tools/smalldev-tools#14]
Converting from Markdown to Org makes it easier to convert to HTML (using Spacemacs) or you can either have a feature to convert directly to HTML from markdown

**Comment by twf-nikhila** [comment]
@ruby-rust-perl HTML to markdown is present, but not the reverse one. 

https://smalldev.tools/html-to-markdown-converter-online

Checking for others. Thank you for feedback @ruby-rust-perl
