### ISSUE TITLE
sort list tool

### ISSUE THREAD

**Issue by saiballo** [smalldev-tools/smalldev-tools#27]
Your site is awesome. What about adding a sort list tool?

**Comment by twf-nikhila** [comment]
@saiballo Thank you

Sure, give an example of sort list and I can add it.

**Comment by saiballo** [comment]
for example, in input, a comma separated list:

House,
Car,
Breakfast,
Arrow,

it will be sorted:

Arrow,
Breakfast,
Car,
House,

**Comment by twf-nikhila** [comment]
@saiballo ok, adding it in the next release in a few days!

**Comment by saiballo** [comment]
amazing!!!!

**Comment by twf-nikhila** [comment]
@saiballo This sorting of list tool is now available.

https://smalldev.tools/sorting-list-online

This online string sorting tool can be used to sort strings alphabetically or by length. Alphabetically sorting in ascending order or alphabetically sorting in descending order or length based sorting in ascending or descending order.


Enjoy 🚀

**Comment by saiballo** [comment]
really a good job!!! thank you very much!
