### ISSUE TITLE
Fix: Cards with different heights

### ISSUE THREAD

**Issue by Ademking** [smalldev-tools/smalldev-tools#7]
![image](https://user-images.githubusercontent.com/12462188/131884638-f5f5e6ec-e46b-42c9-adb8-f2d32c3de65e.png)

Cards do not have the same height, which is not pretty (I think) ... Maybe try to use the same fixed height for every card.

Cool project by the way. Keep up the good work

**Comment by twf-nikhila** [comment]
@Ademking ahhh...thanks for letting me know this.  Will check and fix.

Thank you for your appreciation. 

Please do share it with your developer's community/friends/collegues.

**Comment by twf-nikhila** [comment]
@Ademking Done!
