### ISSUE TITLE
Feature: JSON generator

### ISSUE THREAD

**Issue by BenRamins** [smalldev-tools/smalldev-tools#9]
something like: https://www.json-generator.com/

**Comment by twf-nikhila** [comment]
@BenRamins This feature is already present but with a different name.

Check this: [Test Data Generator](https://smalldev.tools/test-data-generator-online)

Here select the columns you need with their type and select output format as JSON and it will work.

You can also set output language like English/French/Spanish and a lot more.

**Comment by twf-nikhila** [comment]
Check and let me know how it goes for you!
